### PR TITLE
feat(to_string_ref): add to_string_ref

### PR DESCRIPTION
**Pull request by igorgue**
And renamed some values because they clash with Python stdlib, I think.

### CODE REVIEW

**Comment by Moosems** [comment]
It is almost ready to merge, could you update the docs?

**Comment by igorgue** [comment]
@Moosems what do you mean?

**Comment by Moosems** [comment]
Each folder has a readme that documents the types/functions.

**Comment by igorgue** [comment]
Sure, I'll take a look later tonight.

**Comment by Moosems** [comment]
@igorgue Any update?

**Comment by igorgue** [comment]
Thanks for the reminder, I forgot about this, I'll get to it tonight.

I'm working on a web server and the last Mojo update broke it so I took a break from Mojo, let me do the docs for this though thank you!

I actually believe there's a better version of this function because it doesn't convert it to null terminated strings.

**Comment by igorgue** [comment]
@Moosems Done, let me know.

**Review by Moosems — APPROVED** [review]

**Comment by Moosems** [comment]
Looks good :).

**Pull request merged**
